#!/bin/bash

export LD_LIBRARY_PATH=$Qt6_DIR_LINUX/lib
export QT_QPA_PLATFORM=xcb


#
# Build new binary
#
cd ../enroute
fastlane linuxBinary
cd build/build-linux-release
ninja attributions
cd ../../../enrouteManual


#
# Create build directory
#
rm -rf build/manualAssets
mkdir -p build/manualAssets

#
# Generate waypoint icons
#
echo "Generating waypoint icons..."
mkdir waypointIcons
rsvg-convert ../enroute/src/flightMap/sprites/AD.svg -o src/05-referencePages/AD.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/AD-GLD.svg -o src/05-referencePages/AD-GLD.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/AD-GRASS.svg -o src/05-referencePages/AD-GRASS.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/AD-INOP.svg -o src/05-referencePages/AD-INOP.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/AD-MIL.svg -o src/05-referencePages/AD-MIL.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/AD-MIL-GRASS.svg -o src/05-referencePages/AD-MIL-GRASS.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/AD-MIL-PAVED.svg -o src/05-referencePages/AD-MIL-PAVED.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/AD-PAVED.svg -o src/05-referencePages/AD-PAVED.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/AD-UL.svg -o src/05-referencePages/AD-UL.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/AD-WATER.svg -o src/05-referencePages/AD-WATER.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/MRP.svg -o src/05-referencePages/MRP.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/NDB.svg -o src/05-referencePages/NDB.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/RP.svg -o src/05-referencePages/RP.png -h 30 -w 30
rsvg-convert ../enroute/src/flightMap/sprites/VOR.svg -o src/05-referencePages/VOR.png -w 30
rsvg-convert ../enroute/src/flightMap/sprites/VOR.svg -o src/05-referencePages/DVOR.png -w 30
rsvg-convert ../enroute/src/flightMap/sprites/VORDME.svg -o src/05-referencePages/VOR-DME.png -w 30
rsvg-convert ../enroute/src/flightMap/sprites/VORDME.svg -o src/05-referencePages/DVOR-DME.png -w 30
rsvg-convert ../enroute/src/flightMap/sprites/VORTAC.svg -o src/05-referencePages/VORTAC.png -w 30
rsvg-convert ../enroute/src/flightMap/sprites/VORTAC.svg -o src/05-referencePages/DVORTAC.png -w 30
rsvg-convert ../enroute/src/icons/waypoints/ic_warning_18px.svg -o src/05-referencePages/NOTAM.png -w 30
rsvg-convert ../enroute/src/icons/waypoints/WP-map.svg -o src/05-referencePages/WP.png -w 10


#
#  License Overview
#
echo "Copy License Overview"
cp ../enroute/generatedSources/licenses_overview.rst src/08-appendix/licenses_overview.rst


#
# Screenshots
#
echo "Generating Screenshot"
LC_ALL=en_US ../enroute/build/build-linux-release/src/enroute --sm
mv 01-*.png src/01-gettingStarted/autogenerated/
mv 02-*.png src/02-tutorialBasic/autogenerated/
mv 03-*.png src/03-tutorialAdvanced/autogenerated/
mv 05-*.png src/05-referencePages/autogenerated/


#
# Privacy policies
#
echo "Generating Privacy Policies Text"
echo "Privacy Policies" >src/08-appendix/03-privacy.rst
echo "================" >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
echo "English" >>src/08-appendix/03-privacy.rst
echo "-------" >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
LC_ALL=EN ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
echo "Deutsche Übersetzung" >>src/08-appendix/03-privacy.rst
echo "--------------------" >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
LC_ALL=DE ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
echo "Traduction en français" >>src/08-appendix/03-privacy.rst
echo "----------------------" >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
LC_ALL=FR ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
echo "Traduzione italiana" >>src/08-appendix/03-privacy.rst
echo "-------------------" >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
LC_ALL=IT ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
echo "Polskie tłumaczenie" >>src/08-appendix/03-privacy.rst
echo "-------------------" >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
LC_ALL=PL ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
echo "Traducción al español" >>src/08-appendix/03-privacy.rst
echo "---------------------" >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
LC_ALL=ES ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>src/08-appendix/03-privacy.rst
echo "" >>src/08-appendix/03-privacy.rst
echo "Authors" >src/08-appendix/04-authors.rst
echo "=======" >>src/08-appendix/04-authors.rst
LC_ALL=EN ../../enroute/build/build-linux-release/src/enroute --string :text/authors.html | pandoc --from=HTML --write=rst >>src/08-appendix/04-authors.rst
