#!/bin/bash

export LD_LIBRARY_PATH=$Qt6_DIR_LINUX/lib
export QT_QPA_PLATFORM=xcb

rm -rf build_manualAssets
mkdir -p build_manualAssets
cd build_manualAssets


#
# Generate waypoint icons
#
echo "Generating waypoint icons..."
mkdir waypointIcons
rsvg-convert ../../enroute/src/flightMap/sprites/AD.svg -o AD.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/AD-GLD.svg -o AD-GLD.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/AD-GRASS.svg -o AD-GRASS.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/AD-INOP.svg -o AD-INOP.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/AD-MIL.svg -o AD-MIL.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/AD-MIL-GRASS.svg -o AD-MIL-GRASS.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/AD-MIL-PAVED.svg -o AD-MIL-PAVED.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/AD-PAVED.svg -o AD-PAVED.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/AD-UL.svg -o AD-UL.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/AD-WATER.svg -o AD-WATER.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/MRP.svg -o MRP.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/NDB.svg -o NDB.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/RP.svg -o RP.png -h 30 -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/VOR.svg -o VOR.png -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/VOR.svg -o DVOR.png -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/VORDME.svg -o VOR-DME.png -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/VORDME.svg -o DVOR-DME.png -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/VORTAC.svg -o VORTAC.png -w 30
rsvg-convert ../../enroute/src/flightMap/sprites/VORTAC.svg -o DVORTAC.png -w 30
rsvg-convert ../../enroute/src/icons/waypoints/ic_warning_18px.svg -o NOTAM.png -w 30
rsvg-convert ../../enroute/src/icons/waypoints/WP-map.svg -o WP.png -w 10
mv *.png ../05-referencePages

#
#  COMMAND pwd
#  COMMAND python3 ${CMAKE_CURRENT_SOURCE_DIR}/generateAttributions.py

#
# Screenshots
#

echo "Generating Screenshot"
#LC_ALL=en_US ../../enroute/build/build-linux-release/src/enroute --sm
#mv 01-*.png ../01-gettingStarted/autogenerated/
#mv 02-*.png ../02-tutorialBasic/autogenerated/
#mv 03-*.png ../03-tutorialAdvanced/autogenerated/
#mv 05-*.png ../05-referencePages/autogenerated/


#
# Privacy policies
#

echo "Generating Privacy Policies Text"
echo "Privacy Policies" >../08-appendix/03-privacy.rst
echo "================" >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
echo "English" >>../08-appendix/03-privacy.rst
echo "-------" >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
LC_ALL=EN ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
echo "Deutsche Übersetzung" >>../08-appendix/03-privacy.rst
echo "--------------------" >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
LC_ALL=DE ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
echo "Traduction en français" >>../08-appendix/03-privacy.rst
echo "----------------------" >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
LC_ALL=FR ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
echo "Traduzione italiana" >>../08-appendix/03-privacy.rst
echo "-------------------" >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
LC_ALL=IT ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
echo "Polskie tłumaczenie" >>../08-appendix/03-privacy.rst
echo "-------------------" >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
LC_ALL=PL ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
echo "Traducción al español" >>../08-appendix/03-privacy.rst
echo "---------------------" >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
LC_ALL=ES ../../enroute/build/build-linux-release/src/enroute --string :text/privacy.html | pandoc --from=HTML --write=rst >>../08-appendix/03-privacy.rst
echo "" >>../08-appendix/03-privacy.rst
echo "Authors" >../08-appendix/04-authors.rst
echo "=======" >>../08-appendix/04-authors.rst
LC_ALL=EN ../../enroute/build/build-linux-release/src/enroute --string :text/authors.html | pandoc --from=HTML --write=rst >>../08-appendix/04-authors.rst
